# Generated by Django 4.1.3 on 2022-11-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_anuncio_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
